#!/usr/bin/env bash

commands=(
'git log --oneline --branches --not --remotes --color'
'git -c color.status=always status --short --branch'
)

out=''

for command in "${commands[@]}"; do
  out="$out$($command)\n\n"
done

echo -e "\\033c$out"

